server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#token:
#  expiration_time: 86400000 #1일
#  secret: mySecretSet123

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id : open-book
          uri : lb://OPEN-BOOK
          predicates:
            - Path=/open-book/**
        - id: user
          uri : lb://USER
          predicates:
            - Path=/user/**
        - id : user
          uri : lb://USER
          predicates:
            - Path=/api/v1/auth/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user/(?<segment>.*), /$\{segment}
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/member
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: refresh