server:
  port: 8081

spring:
  application:
    name: config
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file://${home}/Desktop/iamdoky/mini-msa-practice
        git:
          uri: https://github.com/iamdoky/mini-msa-practice.git
