server:
  port: 8081
spring:
  application:
    name: config
  profiles:
    active: native
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        native:
          search-locations: file://${home}/Desktop/iamdoky/mini-msa-practice
        git:
          uri: https://github.com/iamdoky/mini-msa-practice.git
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh